let s:flavors = glob('./.vim-flavor/deps/*')
let s:rtps = filter(split(s:flavors, '\n'), 'isdirectory(v:val)')
let s:rtp = split(&runtimepath, ',')
let &runtimepath = join([] + s:rtp + s:rtps, ',')

set rtp+=.
runtime ruby-refactoring.vim

set expandtab
set sw=2
set sts=2
filetype plugin indent on
