language: ruby
bundler_args: --without doc dev --jobs=3 --retry=3
cache:
  - bundler
  - directories:
    - test/feature_files
rvm:
 - 2.0.0
 - 2.1.3
env:
  - CI=true
branches:
  only:
    - master
    - dev
    - refactor
script: bundle exec rake ci
